name: Build Docker images

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
    tags:
      - "v*"

jobs:
  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        shell: bash
        run: |
          shellcheck **/*.sh

  build:
    runs-on: ubuntu-24.04
    needs:
      - shellcheck

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build the Docker image
        shell: bash
        run: |
          docker buildx build . \
            --platform linux/amd64,linux/arm64 \
            --file Dockerfile \
            --tag engineervix/docker-zulip:9.1.1-$(date +'%Y%m%d%H%M%S')
